// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-realworld/internal/conf"
	"kratos-realworld/internal/data/user"
	"kratos-realworld/internal/data_struct"
	"kratos-realworld/internal/server"
	"kratos-realworld/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, data *conf.Data, jwt *conf.JWT, logger log.Logger) (*kratos.App, func(), error) {
	db := data_struct.NewDatabase(data)
	client := data_struct.NewCache(data)
	data_structData := data_struct.NewData(db, client)
	userLogRepo := user.NewUserLogRepo(data_structData, logger)
	conduitService := service.NewConduitService(userLogRepo, logger)
	httpServer := server.NewHTTPServer(confServer, jwt, conduitService, logger)
	grpcServer := server.NewGRPCServer(confServer, conduitService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
